### ISSUE TITLE
Can't choose pages which have "Show in menus?" unticked

### ISSUE THREAD

**Issue by BradyEdgar94** [Zauberfisch/silverstripe-easy-linkfield#3]
Hi there,

I noticed that none of my pages that have "Show in menus?" unticked in their page settings aren't showing in the dropdown when choosing an internal link. Is there a way to show all pages instead of just pages visible in the menu?

Thanks, sorry to bug you again :)

**Comment by Zauberfisch** [comment]
Sorry, that was a big oversight on my side. But an easy fix, I've just published a new release. Please let me know if it's working now after updating.
